name: extensions_pack
description: Collection of dart extensions.

version: 1.2.2

repository: https://github.com/jorgelrj/extensions_pack

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
