name: extensions_pack
description: Collection of dart extensions.

version: 2.0.3

repository: https://github.com/jorgelrj/extensions_pack

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  recase: ^4.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  my_linter: ^0.0.4


flutter: null
